/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopapplication;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yannick
 */
public class AddBook extends javax.swing.JFrame {
        String ImgPath;
    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
        Show_Product_In_JTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bookID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bookName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bookPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bookImage = new javax.swing.JLabel();
        imagePicker = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(java.awt.Color.pink);
        jLabel1.setFont(new java.awt.Font("AR DESTINE", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dalt0n's Bookstore");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD MORE BOOK TITLES");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 280, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("BOOK ID:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 80, 80, 17);

        bookID.setForeground(java.awt.Color.white);
        jPanel1.add(bookID);
        bookID.setBounds(140, 70, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("BOOK NAME:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 140, 100, 17);

        bookName.setForeground(java.awt.Color.white);
        jPanel1.add(bookName);
        bookName.setBounds(140, 130, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("AUTHOR:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 200, 80, 17);

        bookPrice.setForeground(java.awt.Color.white);
        jPanel1.add(bookPrice);
        bookPrice.setBounds(140, 250, 210, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("PICTURE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 290, 70, 17);
        jPanel1.add(bookImage);
        bookImage.setBounds(10, 310, 340, 180);

        imagePicker.setBackground(new java.awt.Color(0, 102, 102));
        imagePicker.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imagePicker.setForeground(java.awt.Color.pink);
        imagePicker.setText("Choose Image");
        imagePicker.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imagePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagePickerActionPerformed(evt);
            }
        });
        jPanel1.add(imagePicker);
        imagePicker.setBounds(170, 500, 110, 23);

        addButton.setBackground(new java.awt.Color(0, 102, 102));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setForeground(java.awt.Color.pink);
        addButton.setText("ADD");
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(60, 540, 110, 23);

        deleteButton.setBackground(new java.awt.Color(0, 102, 102));
        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteButton.setForeground(java.awt.Color.pink);
        deleteButton.setText("DELETE");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(280, 540, 110, 23);

        jTable1.setBackground(new java.awt.Color(0, 102, 102));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setForeground(java.awt.Color.white);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "BOOK ID", "BURGERNAME", "AUTHOR", "PRICE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 70, 430, 430);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("PRICE:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 260, 80, 17);

        author.setForeground(java.awt.Color.white);
        jPanel1.add(author);
        author.setBounds(140, 190, 210, 30);

        logoutButton.setBackground(new java.awt.Color(0, 102, 102));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setForeground(java.awt.Color.pink);
        logoutButton.setText("LOGOUT");
        logoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(710, 540, 90, 25);

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.pink);
        backButton.setText("BACK");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(610, 540, 90, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagePickerActionPerformed
        // TODO add your handling code here:
        JFileChooser file= new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty(("user.home"))));

        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.images","jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);

        if (result== JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path= selectedFile.getAbsolutePath();

            bookImage.setIcon(ResizeImage(path,null));
            ImgPath = path;

        }
        else
        System.out.println("No File Seected");

    }//GEN-LAST:event_imagePickerActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        String BookID= bookID.getText();
        String BurgerName= bookName.getText();
        String Author=author.getText().trim();
        Float price=Float.parseFloat(bookPrice.getText());
        try{
            Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop", "root", "yannick777");
            Statement st= (Statement) con.createStatement();
            ResultSet res = st.executeQuery("SELECT BookName FROM books");
            int insert=1;
            while(res.next()){
                if (BurgerName.equals(res.getString("BookName"))){
                    JOptionPane.showMessageDialog(null, "This Book already exists!");
                    insert=0;
                    break;
                }

            }
            if(insert==1)
            {
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("INSERT INTO books(BookID,BookName,Author,Price,BurgerPicture)"+"values(?,?,?,?,?)");
                ps.setString(1, BookID);
                ps.setString(2, BurgerName);
                ps.setString(3,Author);

                ps.setFloat(4, price);

                InputStream img = new FileInputStream(new File(ImgPath));
                ps.setBlob(5, img);
                ps.executeUpdate();

                Show_Product_In_JTable();

                JOptionPane.showMessageDialog(null,("Data Inserted"));
            }
            con.close();
        }

        catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }

        bookName.setText(null);
        bookID.setText(null);
        bookPrice.setText(null);

    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(bookID.getText().equals(""))
        {
            try
            {
                Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
                PreparedStatement ps= (PreparedStatement) con.prepareStatement("DELETE FROM books WHERE BookID=?");
                String BID = bookID.getText().trim();

                ps.setString(1,BID);
                ps.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                int index = jTable1.getSelectedRow();
                model.removeRow(index);

                JOptionPane.showMessageDialog(null, "Data Successfully Deleted");
            }
            catch(SQLException e){
                Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE,null,e);
                JOptionPane.showMessageDialog(null,"Data Not Deleted");
            }
        }
        else
        {   JOptionPane.showMessageDialog(null,"Data Not Deleted"); }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index= jTable1.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_jTable1MouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        logout newlogout=new logout();
        newlogout.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HomePage back = new HomePage();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    
    public class Books{
        private String BID;
        private String BName;
        private float BPrice;
        private String BAuthor;
        private byte[] BPicture;

        public Books(String bBID, String bBName, String bAuthor, float bBPrice, byte[] bBPicture)
        {
            this.BID=bBID;
            this.BName=bBName;
            this.BAuthor=bAuthor;
            this.BPrice=bBPrice;
          
            this.BPicture=bBPicture;
        }
    
        public String getBID()
        {   return BID;  }

        public String getBName()
        {   return BName;   }
        
        public String getBAuthor()
        {   return BAuthor;   }

        public float getBPrice()
        {   return BPrice;  }

        public byte[] getBPicture()
        {   return BPicture;    }
    
    }
    
    public ImageIcon ResizeImage(String imagePath,byte[] pic)
    {ImageIcon myImage=null;
    
    if (imagePath!=null)
    {
      myImage= new ImageIcon(imagePath);  
    }
    else
    {
        myImage= new ImageIcon(pic);
    }
    Image img= myImage.getImage();
    Image img2= img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(img2);
    return image;
    
    }
    
    public void Show_Product_In_JTable()
    {
        Delete_from_Table();
        
        ArrayList<Books> list= getProductList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Object[] row = new Object[4];
        
        for (int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getBID();
            row[1]=list.get(i).getBName();
             row[2]=list.get(i).getBAuthor();
            
            row[3]=list.get(i).getBPrice();
            model.addRow(row);
        }
    }
    
    public ArrayList<Books> getProductList()
    {   
            ArrayList<Books> productList= new ArrayList<Books>();
            try
            {
                Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
                String query= "SELECT* FROM books";
                
                Statement st= (Statement) con.createStatement();
                ResultSet rs=st.executeQuery(query);
                
                Books product;
                
                while(rs.next())
                {
                    product=new Books(rs.getString("BookID"), rs.getString("BookName"), rs.getString("Author"), Float.parseFloat(rs.getString("Price")), rs.getBytes("BookPicture"));
                    productList.add(product);
                    
                }
            }
            catch(SQLException ex)
            {   Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE, null, ex);     }
            
            
           return productList;
    }
    
    public void Delete_from_Table()
    {
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.getDataVector().removeAllElements();
    }
    
     public void ShowItem(int index)
    {
        bookID.setText(getProductList().get(index).getBID());
        bookName.setText(getProductList().get(index).getBName());
        author.setText(getProductList().get(index).getBAuthor());
        bookPrice.setText(Float.toString(getProductList().get(index).getBPrice()));
        bookImage.setIcon(ResizeImage(null,getProductList().get(index).getBPicture()));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField author;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookID;
    private javax.swing.JLabel bookImage;
    private javax.swing.JTextField bookName;
    private javax.swing.JTextField bookPrice;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton imagePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
