/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Yannick
 */
public class AvailableBooks extends javax.swing.JFrame {

    /**
     * Creates new form AvailableBooks
     */
    public AvailableBooks() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookName = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bookrPrice = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        bookImage = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to our bookstore, we are confident we can provide your literary needs.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 620, 920, 29);

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AVAILABLE BOOKS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 40, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Book ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 110, 54, 17);

        bookName.setBackground(new java.awt.Color(0, 102, 102));
        bookName.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bookName.setForeground(java.awt.Color.pink);
        bookName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bookNameItemStateChanged(evt);
            }
        });
        bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameActionPerformed(evt);
            }
        });
        jPanel1.add(bookName);
        bookName.setBounds(20, 160, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Price:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 220, 34, 17);

        bookrPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookrPrice.setForeground(java.awt.Color.white);
        jPanel1.add(bookrPrice);
        bookrPrice.setBounds(110, 210, 90, 40);

        bookID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookID.setForeground(java.awt.Color.white);
        jPanel1.add(bookID);
        bookID.setBounds(120, 100, 70, 40);

        jLabel5.setFont(new java.awt.Font("AR DELANEY", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.pink);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HAPPY VIEWING !!!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 390, 240, 31);

        orderButton.setBackground(new java.awt.Color(0, 102, 102));
        orderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderButton.setForeground(java.awt.Color.pink);
        orderButton.setText("CLICK TO ORDER");
        orderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel1.add(orderButton);
        orderButton.setBounds(420, 390, 140, 23);
        jPanel1.add(bookImage);
        bookImage.setBounds(370, 60, 360, 290);

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.pink);
        backButton.setText("BACK");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(590, 390, 90, 23);

        jLabel1.setBackground(java.awt.Color.pink);
        jLabel1.setFont(new java.awt.Font("AR DESTINE", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dalt0n's Bookstore");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bookNameItemStateChanged
        // TODO add your handling code here:
        Object selectedItem=bookName.getSelectedItem();
        String BookName=selectedItem.toString().trim();
        String bookIDStored="";
        float price;
        String pprice="";
        boolean verify=true;
        byte[] imagedata=null;

        try
        {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
            Statement st= (Statement) con.createStatement();
            ResultSet res= st.executeQuery("SELECT * FROM books");

            while(res.next()){
                bookIDStored=res.getString("BookID").trim();
                String burgerNameStored= res.getString("BookName").trim();
                price=res.getFloat("Price");
                pprice=Float.toString(price);
                imagedata= res.getBytes("BookPicture");

                if((BookName.equals(burgerNameStored)))
                {
                    verify=true;
                    break;
                }
                else
                {
                    verify=false;
                }
            }

            if(verify==true)
            {
                ImageIcon format =new ImageIcon(imagedata);

                bookImage.setIcon(format);
                bookID.setText(bookIDStored);
                bookrPrice.setText(pprice);
            }

            con.close();
        }
        catch(SQLException ex){
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_bookNameItemStateChanged

    private void bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bookNameActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Orders newOrders=new Orders();
        newOrders.setVisible(true);

    }//GEN-LAST:event_orderButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        HomePage back = new HomePage();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    
    
    public void fillCombo(){
    try
    {
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
         // Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root", "yannick777");
        Statement st=(Statement) con.createStatement();
        ResultSet res=st.executeQuery("SELECT * FROM books");
        while(res.next()){
        String name= res.getString("BookName");
        bookName.addItem(name);
        }
    }
    catch(SQLException ex)
    {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);
    }
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvailableBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookID;
    private javax.swing.JLabel bookImage;
    private javax.swing.JComboBox<String> bookName;
    private javax.swing.JLabel bookrPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orderButton;
    // End of variables declaration//GEN-END:variables
}
