/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yannick
 */
public class ManageUsers extends javax.swing.JFrame {

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        newRole = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginButton1 = new javax.swing.JButton();
        username1 = new javax.swing.JComboBox<>();
        username = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        currentRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(java.awt.Color.pink);
        jLabel1.setFont(new java.awt.Font("AR DESTINE", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dalt0n's Bookstore");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshopapplication/manageUser.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 70, 360, 290);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("CURRENT ROLE:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 170, 120, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("USERNAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 100, 74, 17);

        saveButton.setBackground(new java.awt.Color(0, 102, 102));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setForeground(java.awt.Color.pink);
        saveButton.setText("SAVE");
        saveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton);
        saveButton.setBounds(80, 310, 90, 25);

        newRole.setBackground(new java.awt.Color(0, 102, 102));
        newRole.setForeground(java.awt.Color.pink);
        newRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrator", "manager", "customer" }));
        jPanel1.add(newRole);
        newRole.setBounds(150, 220, 130, 40);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("AR DELANEY", 1, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.pink);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("You are welcome !!!");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(-10, 390, 330, 31);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshopapplication/Webp.net-resizeimage.jpg"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(350, 10, 300, 450);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("ROLE:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 190, 39, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("USERNAME:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 100, 74, 17);

        loginButton1.setBackground(new java.awt.Color(0, 102, 102));
        loginButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton1.setForeground(java.awt.Color.pink);
        loginButton1.setText("SAVE");
        loginButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton1);
        loginButton1.setBounds(100, 310, 90, 25);

        jPanel2.add(username1);
        username1.setBounds(150, 90, 130, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        username.setBackground(new java.awt.Color(0, 102, 102));
        username.setForeground(java.awt.Color.pink);
        jPanel1.add(username);
        username.setBounds(150, 90, 130, 40);

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.pink);
        backButton.setText("BACK");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(190, 310, 90, 25);

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MANAGE USERS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 200, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("NEW ROLE:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 230, 90, 17);

        currentRole.setBackground(new java.awt.Color(0, 102, 102));
        currentRole.setForeground(java.awt.Color.pink);
        jPanel1.add(currentRole);
        currentRole.setBounds(150, 160, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            String Username= username.getSelectedItem().toString().trim();
            String Role= newRole.getSelectedItem().toString().trim();
            

            //Create a connection to the database
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
            Statement st=(Statement) con.createStatement();
         //   ResultSet res=st.executeQuery("SELECT username,password,Role FROM registration");

            //select the items in the database table one after the other
            String update="UPDATE registration SET Role='"+Role+"' WHERE username = '"+Username+"' " ;     
            
            st.executeUpdate(update);
            con.close();
            JOptionPane.showMessageDialog(null, "Successfully Updated Role");
        }
        catch (SQLException ex){
            Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE,null,ex);
            
            username.setSelectedItem(null);
            newRole.setSelectedItem(null);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HomePage back = new HomePage();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    
   public void fillCombo(){
    try
    {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
        Statement st = (Statement) con.createStatement();
        ResultSet res= st.executeQuery("SELECT * FROM registration");
        while(res.next()){
        String Username=res.getString("username");
        String CurrentRole=res.getString("Role");
        currentRole.setText(CurrentRole);
        username.addItem(Username);
        } 
    }
    catch(SQLException ex)
    {    Logger.getLogger(loginPage.class.getName()).log(Level.SEVERE,null,ex);
    }
   } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel currentRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton1;
    private javax.swing.JComboBox<String> newRole;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> username;
    private javax.swing.JComboBox<String> username1;
    // End of variables declaration//GEN-END:variables
}
