/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yannick
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
           fillCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        author = new javax.swing.JTextField();
        bookName = new javax.swing.JComboBox<>();
        bookPrice = new javax.swing.JLabel();
        bookQuantity = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        bookImage = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(java.awt.Color.pink);
        jLabel1.setFont(new java.awt.Font("AR DESTINE", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dalt0n's Bookstore");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLACE ORDERS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("USERNAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 100, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("PASSWORD:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 160, 80, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("BOOK PRICE:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 300, 110, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("AUTHOR:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 260, 120, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("QUANTIY:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 350, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("ADDRESS:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 400, 100, 17);

        logoutButton.setBackground(new java.awt.Color(0, 102, 102));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutButton.setForeground(java.awt.Color.pink);
        logoutButton.setText("LOGOUT");
        logoutButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton);
        logoutButton.setBounds(620, 510, 90, 25);
        jPanel1.add(author);
        author.setBounds(200, 250, 210, 30);

        bookName.setBackground(new java.awt.Color(0, 102, 102));
        bookName.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bookName.setForeground(java.awt.Color.pink);
        bookName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bookNameItemStateChanged(evt);
            }
        });
        bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameActionPerformed(evt);
            }
        });
        jPanel1.add(bookName);
        bookName.setBounds(220, 200, 190, 30);

        bookPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookPrice.setText("0.00");
        jPanel1.add(bookPrice);
        bookPrice.setBounds(220, 290, 90, 40);
        jPanel1.add(bookQuantity);
        bookQuantity.setBounds(210, 350, 60, 20);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 390, 210, 110);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("BOOK TITLE:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 210, 80, 17);
        jPanel1.add(username);
        username.setBounds(200, 100, 210, 30);
        jPanel1.add(bookImage);
        bookImage.setBounds(440, 110, 290, 280);

        orderButton.setBackground(new java.awt.Color(0, 102, 102));
        orderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderButton.setForeground(java.awt.Color.pink);
        orderButton.setText("ORDER NOW");
        orderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel1.add(orderButton);
        orderButton.setBounds(240, 510, 120, 23);

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.pink);
        backButton.setText("BACK");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(520, 510, 90, 25);
        jPanel1.add(password);
        password.setBounds(200, 150, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        logout newlogoutPage = new logout();
        newlogoutPage.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void bookNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bookNameItemStateChanged
        // TODO add your handling code here:
        Object selectedItem=bookName.getSelectedItem();
        String BookName=selectedItem.toString().trim();
        //  String burgerIDStored="";
        float price;
        String pprice="", Author="";
        boolean verify=true;
        byte[] imagedata=null;

        try
        {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
            Statement st= (Statement) con.createStatement();
            ResultSet res= st.executeQuery("SELECT * FROM books");

            while(res.next()){
                //      burgerIDStored=res.getString("BurgerID").trim();
                String bookNameStored= res.getString("BookName").trim();
                Author=res.getString("Author");
                price=res.getFloat("Price");
                pprice=Float.toString(price);
                imagedata= res.getBytes("BookPicture");

                if((BookName.equals(bookNameStored)))
                {
                    verify=true;
                    break;
                }
                else
                {
                    verify=false;
                }
            }

            if(verify==true)
            {
                ImageIcon format =new ImageIcon(imagedata);

                bookImage.setIcon(format);
                author.setText(Author);
                //    burgerID.setText(burgerIDStored);
                bookPrice.setText(pprice);
            }

            con.close();
        }
        catch(SQLException ex){
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_bookNameItemStateChanged

    private void bookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:

        String Username=username.getText().trim();
        String Password=password.getText().trim();
        //Integer Quantity=Integer.parseInt(quantity.getText().trim());
        Integer Quantity1=Integer.parseInt(bookQuantity.getValue().toString());
        String Address=address.getText().trim();
        String Author=author.getText().trim();
        String BookName=bookName.getSelectedItem().toString().trim();

        if(!Username.equals("")&&!Password.equals("")&&!Address.equals("")&&!Author.equals("")&&!BookName.equals("") &&Quantity1 !=null )
        {
            try
            {
                Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
                Statement st =(Statement) con.createStatement();
                String insert="INSERT INTO ordertable VALUES('"+Username+"','"+Password+"','"+BookName+"','"+Author+"','"+Quantity1+"','"+Address+"')";
                st.executeUpdate(insert);

                JOptionPane.showMessageDialog(null, "Order Successful.");

            }
            catch(SQLException ex)
            {   Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex); }

            username.setText("");
            password.setText("");
            // burgerQuantity.set
            address.setText("");
            bookName.setSelectedItem("");
             author.setText("");

        }
        else
        {   JOptionPane.showMessageDialog(null, "All fields must be filled to order successfully ");  }

    }//GEN-LAST:event_orderButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HomePage back= new HomePage();
        back.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    
     public void fillCombo()
    {
        try{
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/bookshop","root","yannick777");
            Statement st=(Statement) con.createStatement();
            ResultSet res= st.executeQuery("SELECT *FROM books");
            while(res.next()){
                String name=res.getString("BookName");
               // String Author=res.getString("Author");
                bookName.addItem(name);
                //author.setText(Author);
                
            }
        }
        catch(SQLException ex)
        {   Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);   }
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField author;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookImage;
    private javax.swing.JComboBox<String> bookName;
    private javax.swing.JLabel bookPrice;
    private javax.swing.JSpinner bookQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton orderButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
