/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pburgerapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Yannick
 */
public class AvailableBurgers extends javax.swing.JFrame {

    /**
     * Creates new form AvailableBurgers
     */
    public AvailableBurgers() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        burgerImage = new javax.swing.JLabel();
        burgerPrice = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        burgerID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        burgerName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tasty Burgers OrderPage");

        jLabel1.setBackground(java.awt.Color.yellow);
        jLabel1.setFont(new java.awt.Font("AR DESTINE", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TASTY BURGERS DELIVERY SYSTEM");
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(null);
        jPanel2.add(burgerImage);
        burgerImage.setBounds(380, 90, 360, 220);

        burgerPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(burgerPrice);
        burgerPrice.setBounds(110, 210, 90, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Price:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 220, 34, 17);

        orderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderButton.setText("CLICK TO ORDER");
        orderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel2.add(orderButton);
        orderButton.setBounds(580, 380, 140, 23);

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AVAILABLE BURGERS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 40, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Burger ID:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 110, 64, 17);

        burgerID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(burgerID);
        burgerID.setBounds(120, 100, 70, 40);

        jLabel5.setFont(new java.awt.Font("AR DELANEY", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HAPPY VIEWING !!!");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 390, 240, 31);

        burgerName.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        burgerName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        burgerName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                burgerNameItemStateChanged(evt);
            }
        });
        burgerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerNameActionPerformed(evt);
            }
        });
        jPanel2.add(burgerName);
        burgerName.setBounds(20, 160, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Orders newOrders=new Orders();
        newOrders.setVisible(true);
                
    }//GEN-LAST:event_orderButtonActionPerformed

    private void burgerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerNameActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_burgerNameActionPerformed

    private void burgerNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_burgerNameItemStateChanged
        // TODO add your handling code here:
         Object selectedItem=burgerName.getSelectedItem();
        String BurgerName=selectedItem.toString().trim();
        String burgerIDStored="";
        float price;
        String pprice="";
        boolean verify=true;
        byte[] imagedata=null;
        
        try
        {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root","yannick777");
        Statement st= (Statement) con.createStatement();
        ResultSet res= st.executeQuery("SELECT * FROM burgers");
        
            while(res.next()){
                burgerIDStored=res.getString("BurgerID").trim();
                String burgerNameStored= res.getString("BurgerName").trim();
                price=res.getFloat("Price");
                pprice=Float.toString(price);
                imagedata= res.getBytes("BurgerPicture");

                if((BurgerName.equals(burgerNameStored)))
                {
                    verify=true;
                    break;
                }
                else
                {
                    verify=false;
                }
            }
            
            if(verify==true)
            {
              ImageIcon format =new ImageIcon(imagedata);
                
                burgerImage.setIcon(format);
                burgerID.setText(burgerIDStored);
                burgerPrice.setText(pprice);
            }
            
            con.close();
        }
        catch(SQLException ex){
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_burgerNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    
    
    public void fillCombo(){
    try
    {
        Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root","yannick777");
         // Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root", "yannick777");
        Statement st=(Statement) con.createStatement();
        ResultSet res=st.executeQuery("SELECT * FROM burgers");
        while(res.next()){
        String name= res.getString("BurgerName");
        burgerName.addItem(name);
        }
    }
    catch(SQLException ex)
    {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);
    }
    
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableBurgers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableBurgers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableBurgers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableBurgers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvailableBurgers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel burgerID;
    private javax.swing.JLabel burgerImage;
    private javax.swing.JComboBox<String> burgerName;
    private javax.swing.JLabel burgerPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton orderButton;
    // End of variables declaration//GEN-END:variables
}
