/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pburgerapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yannick
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
        fillCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        burgerID = new javax.swing.JLabel();
        burgerName = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        burgerSize = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        burgerPrice = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        burgerImage = new javax.swing.JLabel();
        burgerQuantity = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(java.awt.Color.yellow);
        jLabel1.setFont(new java.awt.Font("AR DESTINE", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TASTY BURGERS DELIVERY SYSTEM");
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(null);

        orderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderButton.setText("ORDER NOW");
        orderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });
        jPanel2.add(orderButton);
        orderButton.setBounds(190, 450, 120, 23);

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 2, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLACE ORDERS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 20, 180, 30);

        burgerID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(burgerID);
        burgerID.setBounds(120, 100, 70, 40);

        burgerName.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        burgerName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        burgerName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                burgerNameItemStateChanged(evt);
            }
        });
        burgerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerNameActionPerformed(evt);
            }
        });
        jPanel2.add(burgerName);
        burgerName.setBounds(210, 150, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DELIVERY ADDRESS:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 320, 150, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TYPE OF ORDER:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 150, 120, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PASSWORD:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 100, 100, 17);

        burgerSize.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        burgerSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "large", "small" }));
        burgerSize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        burgerSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                burgerSizeItemStateChanged(evt);
            }
        });
        burgerSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerSizeActionPerformed(evt);
            }
        });
        jPanel2.add(burgerSize);
        burgerSize.setBounds(210, 230, 190, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("SIZE:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 230, 80, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("USERNAME:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 50, 80, 17);
        jPanel2.add(username);
        username.setBounds(190, 50, 210, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("QUANTITY:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 280, 80, 17);

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(exitButton);
        exitButton.setBounds(690, 440, 90, 23);

        burgerPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        burgerPrice.setText("0.00");
        jPanel2.add(burgerPrice);
        burgerPrice.setBounds(210, 180, 90, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Price:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 190, 34, 17);
        jPanel2.add(burgerImage);
        burgerImage.setBounds(490, 110, 280, 220);
        jPanel2.add(burgerQuantity);
        burgerQuantity.setBounds(210, 280, 50, 20);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(200, 310, 210, 110);
        jPanel2.add(password);
        password.setBounds(190, 90, 210, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void burgerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_burgerNameActionPerformed

    private void burgerNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_burgerNameItemStateChanged
        // TODO add your handling code here:
        Object selectedItem=burgerName.getSelectedItem();
        String BurgerName=selectedItem.toString().trim();
      //  String burgerIDStored="";
        float price;
        String pprice="";
        boolean verify=true;
        byte[] imagedata=null;

        try
        {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root","yannick777");
            Statement st= (Statement) con.createStatement();
            ResultSet res= st.executeQuery("SELECT * FROM burgers");

            while(res.next()){
          //      burgerIDStored=res.getString("BurgerID").trim();
                String burgerNameStored= res.getString("BurgerName").trim();
                price=res.getFloat("Price");
                pprice=Float.toString(price);
                imagedata= res.getBytes("BurgerPicture");

                if((BurgerName.equals(burgerNameStored)))
                {
                    verify=true;
                    break;
                }
                else
                {
                    verify=false;
                }
            }

            if(verify==true)
            {
                ImageIcon format =new ImageIcon(imagedata);

                burgerImage.setIcon(format);
            //    burgerID.setText(burgerIDStored);
                burgerPrice.setText(pprice);
            }

            con.close();
        }
        catch(SQLException ex){
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_burgerNameItemStateChanged

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        
        String Username=username.getText().trim();
        String Password=password.getText().trim();
        //Integer Quantity=Integer.parseInt(quantity.getText().trim());
        Integer Quantity1=Integer.parseInt(burgerQuantity.getValue().toString());
        String Address=address.getText().trim();
        String BurgerSize=burgerSize.getSelectedItem().toString().trim();
        String Ordertype=burgerName.getSelectedItem().toString().trim();
        
        if(!Username.equals("")&&!Password.equals("")&&!Address.equals("")&&!BurgerSize.equals("")&&!Ordertype.equals("") &&Quantity1 !=null )
        {
            try
            {
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root","yannick777");
            Statement st =(Statement) con.createStatement();
            String insert="INSERT INTO ordertable VALUES('"+Username+"','"+Password+"','"+Ordertype+"','"+BurgerSize+"','"+Quantity1+"','"+Address+"')";
            st.executeUpdate(insert);
            
            JOptionPane.showMessageDialog(null, "Order Successful.");
        
            }
            catch(SQLException ex)
            {   Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex); }
        
            username.setText("");
            password.setText("");
           // burgerQuantity.set
            address.setText("");
            burgerSize.setSelectedItem(null);
           // burgerName.setSelectedItem(null);
            
        }
        else
        {   JOptionPane.showMessageDialog(null, "All fields must be filled to order successfully ");  }
        
       
        
    }//GEN-LAST:event_orderButtonActionPerformed

    private void burgerSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_burgerSizeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_burgerSizeItemStateChanged

    private void burgerSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_burgerSizeActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        logout newlogout= new logout();
        newlogout.setVisible(true);
        
        
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void fillCombo()
    {
        try{
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pburgerapp","root","yannick777");
            Statement st=(Statement) con.createStatement();
            ResultSet res= st.executeQuery("SELECT *FROM burgers");
            while(res.next()){
                String name=res.getString("BurgerName");
                burgerName.addItem(name);
            }
        }
        catch(SQLException ex)
        {   Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE,null,ex);   }
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel burgerID;
    private javax.swing.JLabel burgerImage;
    private javax.swing.JComboBox<String> burgerName;
    private javax.swing.JLabel burgerPrice;
    private javax.swing.JSpinner burgerQuantity;
    private javax.swing.JComboBox<String> burgerSize;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
